apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: meet-sync
build:
  artifacts:
    - image: vinayakbhat430learn/meet-sync-client
      context: client
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
      docker:
        dockerfile: Dockerfile
    - image: vinayakbhat430learn/meet-sync-server
      context: server
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/client-srv.yaml
    - infra/k8s/meet-sync-backend-srv.yaml
    - infra/k8s/meet-sync-mongo-srv.yaml
